import { Router, Request, Response } from 'express';
import { getSession } from '../utils/sessionStore';

const router = Router();

router.get('/:sessionId/cif', (req: Request, res: Response) => {
  const { sessionId } = req.params;
  const session = getSession(sessionId);
  if (!session?.generatedCif) { res.status(404).json({ error: 'CIF file not found. Run convert first.' }); return; }

  const buf = Buffer.from(session.generatedCif, 'utf-8');
  res.set({
    'Content-Type': 'text/plain; charset=UTF-8',
    'Content-Disposition': `attachment; filename="catalog-${sessionId.slice(0, 8)}.cif"`,
    'Content-Length': String(buf.length),
  });
  res.send(buf);
});

router.get('/:sessionId/cxml', (req: Request, res: Response) => {
  const { sessionId } = req.params;
  const session = getSession(sessionId);

  // Full multipart MIME transaction (generated by CXML_FILE output)
  if (session?.generatedCxmlMultipart && session.generatedCxmlBoundary) {
    const buf = session.generatedCxmlMultipart;
    res.set({
      'Content-Type': 'application/octet-stream',
      'Content-Disposition': `attachment; filename="catalog-upload-${sessionId.slice(0, 8)}.mime"`,
      'Content-Length': String(buf.length),
    });
    res.send(buf);
    return;
  }

  // Fallback: XML envelope only (from ARIBA_POST flow)
  if (!session?.generatedCxml) { res.status(404).json({ error: 'cXML file not found. Run convert first.' }); return; }
  const buf = Buffer.from(session.generatedCxml, 'utf-8');
  res.set({
    'Content-Type': 'application/xml; charset=UTF-8',
    'Content-Disposition': `attachment; filename="catalog-${sessionId.slice(0, 8)}.xml"`,
    'Content-Length': String(buf.length),
  });
  res.send(buf);
});

export default router;
