import { CatalogItem } from '../types/catalog';

// Maps CIF 3.0 Excel column headers to CatalogItem field names
export const CIF30_COLUMN_MAP: Record<string, keyof CatalogItem> = {
  'supplier id': 'supplierId',
  'supplierid': 'supplierId',
  'supplier part id': 'supplierPartId',
  'supplierpartid': 'supplierPartId',
  'manufacturer part id': 'manufacturerPartId',
  'manufacturerpartid': 'manufacturerPartId',
  'item description': 'itemDescription',
  'itemdescription': 'itemDescription',
  'spsc code': 'unspscCode',
  'unspsc code': 'unspscCode',
  'unspsccode': 'unspscCode',
  'spsccode': 'unspscCode',
  'unit price': 'unitPrice',
  'unitprice': 'unitPrice',
  'unit of measure': 'unitOfMeasure',
  'unitofmeasure': 'unitOfMeasure',
  'lead time': 'leadTime',
  'leadtime': 'leadTime',
  'manufacturer name': 'manufacturerName',
  'manufacturername': 'manufacturerName',
  'supplier url': 'supplierUrl',
  'supplierurl': 'supplierUrl',
  'manufacturer url': 'manufacturerUrl',
  'manufacturerurl': 'manufacturerUrl',
  'market price': 'marketPrice',
  'marketprice': 'marketPrice',
  'supplier part auxiliary id': 'supplierPartAuxiliaryId',
  'supplierpartauxiliaryid': 'supplierPartAuxiliaryId',
  'language': 'language',
  'currency': 'currency',
  'short name': 'shortName',
  'shortname': 'shortName',
  'image': 'imageUrl',
  'thumbnail': 'thumbnailUrl',
  'price unit quantity': 'priceUnitQuantity',
  'priceunitquantity': 'priceUnitQuantity',
  'price unit': 'priceUnit',
  'priceunit': 'priceUnit',
  'unit conversion': 'unitConversion',
  'unitconversion': 'unitConversion',
  'pricing description': 'pricingDescription',
  'pricingdescription': 'pricingDescription',
  'punchout enabled': 'punchOutEnabled',
  'punchout level': 'punchOutLevel',
  'punchoutlevel': 'punchOutLevel',
};

// Maps CMS Realms top-level column headers to CatalogItem field names
export const CMS_COLUMN_MAP: Record<string, keyof CatalogItem> = {
  'supplier id': 'supplierId',
  'supplier part id': 'supplierPartId',
  'manufacturer part id': 'manufacturerPartId',
  'item description': 'itemDescription',
  'unspsc': 'unspscCode',
  'unit price': 'unitPrice',
  'unit of measure': 'unitOfMeasure',
  'currency': 'currency',
  'lead time': 'leadTime',
  'manufacturer name': 'manufacturerName',
  'supplier url': 'supplierUrl',
  'manufacturer url': 'manufacturerUrl',
  'market price': 'marketPrice',
  'supplier part auxiliary id': 'supplierPartAuxiliaryId',
  'language': 'language',
  'short name': 'shortName',
  'item spec': 'itemSpec',
  'keywords': 'keywords',
  'eclass 7.1': 'unspscCode', // fallback if UNSPSC not present
  'punchout enabled': 'punchOutEnabled',
  'punchoutlevel': 'punchOutLevel',
  'punchout level': 'punchOutLevel',
  'territory available': 'territoryAvailable',
  'start date': 'startDate',
  'end date': 'endDate',
  'effective date': 'effectiveDate',
  'expiration date': 'expirationDate',
  'is preferred item': 'isPreferredItem',
  'ispreferred': 'isPreferredItem',
  'promotion rank': 'promotionRank',
  'hazardousmaterials': 'hazardousMaterials',
  'hazardous materials': 'hazardousMaterials',
  'green': 'green',
  'ispartial': 'isPartial',
  'is partial': 'isPartial',
  'delete': 'delete',
  'inkitonly': 'inKitOnly',
  'in kit only': 'inKitOnly',
  'isinternalpartid': 'isInternalPartId',
  'is internal part id': 'isInternalPartId',
  'defaultrelevance': 'defaultRelevance',
  'default relevance': 'defaultRelevance',
  'content unit': 'contentUnit',
  'packing quantity': 'packingQuantity',
  'minimum quantity': 'minimumQuantity',
  'quantity interval': 'quantityInterval',
  'price unit quantity': 'priceUnitQuantity',
  'price unit': 'priceUnit',
  'unit conversion': 'unitConversion',
  'parametric name': 'parametricName',
  'parametric data': 'parametricData',
};

// Regex to detect repeating group suffix: "PriceConfiguration-1" → ["PriceConfiguration", 1]
export const REPEATING_GROUP_REGEX = /^(.+)-(\d+)$/;

export function normalizeHeader(header: string): string {
  return header.trim().toLowerCase().replace(/\s+/g, ' ');
}
