// UN/CEFACT common unit codes (subset of ~200 most used)
export const UNUOM_CODES = new Set([
  'EA','BX','CS','PK','BG','BT','BL','BO','CA','CT','CY','DR','DZ',
  'FT','GL','GR','HR','IN','KG','KM','L','LB','LT','M','M2','M3',
  'MG','MI','ML','MM','MON','MTK','MTQ','MTR','NMP','OZ','PA','PC',
  'PF','PG','PL','PR','PT','QT','RL','RM','ROL','SA','SET','SH',
  'ST','SYR','T','TN','TNE','TR','TU','UN','VL','WK','YD','YR',
  'AMP','BAR','BIT','BTU','CAL','CEL','CMK','CMQ','CMT','DAY',
  'DEC','DEG','GLL','GME','GRM','HLT','HUR','INH','INK','INQ',
  'JOU','KEL','KGM','KMH','KNT','KPA','KWH','LBR','LTR','LUX',
  'MGM','MIN','MLT','MMT','MOL','MPA','MPH','MTK','NMP','NUM',
  'ONZ','OZA','PAL','PIE','PPM','RAD','RPM','SEC','SMI','SQF',
  'SQI','SQM','SQY','TAH','TON','VLT','WAT','WHR','WSD','4G',
  'ACR','ANN','AVP','BFT','BLL','BPM','BTU','C62','CCT','CDL',
  'CMQ','CNP','CTM','CUR','CWI','CWT','D30','D61','D74','DAD',
  'DAY','DEC','DLT','DPC','DPR','DRA','DWT','E01','E48','FBM',
  'FBR','FH','FLD','FOT','FTK','FTQ','GFI','GIA','GIC','GII',
  'GLD','GLI','GNS','GP','GRM','GRN','GRO','GWH','HAR','HBA',
  'HBX','HGM','HH','HIU','HLT','HMQ','HMT','HPA','HTZ','HUR',
  'INH','INQ','ISD','IU','IV','J2','JOU','JR','KA','KD','KDW',
  'KEL','KGM','KGS','KHZ','KJO','KL','KMK','KMQ','KNI','KNM',
  'KNS','KNT','KPA','KPH','KPO','KPP','KSD','KSH','KT','KVA',
  'KVR','KVT','KW','KWH','KWT','KX','L2','LA','LBR','LBT','LD',
  'LEF','LF','LH','LK','LM','LN','LO','LP','LPA','LR','LS','LTN',
  'LTR','LUM','LUX','M4','MAL','MAM','MAW','MBE','MBF','MBT',
  'MCL','MCM','MGM','MHZ','MIK','MIL','MIN','MIO','MIU','MKM',
  'MLT','MMK','MMQ','MMT','MOL','MPA','MPH','MPL','MQH','MQS',
  'MSK','MTK','MTQ','MTR','MTS','MVA','MWH','N3','NAR','NBB',
  'NCL','NEW','NMP','NMQ','NNI','NPL','NPR','NPT','NRL','NT',
  'NTU','NX','OA','OHM','ON','ONZ','OZA','OZI','P0','P1','P2',
  'PAL','PD','PFL','PGL','PI','PIE','PK','PLA','PLL','PO','PQ',
  'PR','PRM','PTD','PTI','PTL','PTN','PU','PV','PW','PY','PZ',
  'Q3','QA','QAN','QB','QD','QH','QK','QR','QT','QTD','QTI','QTL',
  'R1','R9','RO','RON','RP','RPM','RT','S3','S4','SAN','SCO',
  'SCR','SD','SET','SG','SIE','SM3','SMI','SQF','SQI','SQM','SQY',
  'SR','SST','ST','STI','STL','STN','STW','SV','SW','SX','T0',
  'TAH','TCU','TI','TIC','TIP','TN','TNE','TON','TP','TPR','TQ',
  'TQD','TRL','TST','TTS','U1','U2','UB','UC','UD','UE','UH',
  'UM','UN','UP','UQ','UR','US','UT','UU','UV','UX','V2','VA',
  'VLT','VP','VS','W2','WAT','WB','WCD','WE','WEB','WEE','WG',
  'WH','WHR','WI','WM','WR','WSD','WTT','X1','YDK','YDQ','YRD'
]);

// ANSI X12 common unit codes
export const ANSI_UOM_CODES = new Set([
  'EA','BX','CS','PK','BG','BT','BL','BO','CA','CT','CY','DR','DZ',
  'FT','GL','GR','HR','IN','KG','KM','L','LB','LT','M','M2','M3',
  'MG','MI','ML','MM','MON','OZ','PA','PC','PF','PG','PL','PR',
  'PT','QT','RL','RM','ROL','SA','SET','SH','ST','T','TN','TR',
  'TU','UN','VL','WK','YD','YR','AMP','BAR','BTU','CAL','CEL',
  'DAY','DEG','GLL','GRM','HLT','HUR','INH','JOU','KEL','KGM',
  'KMH','KNT','KPA','KWH','LBR','LTR','LUX','MGM','MIN','MLT',
  'MMT','MOL','MPA','MPH','PAL','PPM','RPM','SEC','SQF','SQM',
  'TON','VLT','WAT','WHR'
]);
